from __future__ import annotations

from codegen.models import GeneratorConfig, TableDefinition
from codegen.renderers.service_renderer import resolve_primary_key
from codegen.utils import build_request_path, render_imports, snake_to_camel


def render_controller(config: GeneratorConfig, table: TableDefinition) -> str:
    primary_key_type, primary_key_field_name = resolve_primary_key(table)
    request_path = build_request_path(config.request_prefix, snake_to_camel(table.name))
    comment = table.comment or table.class_name
    imports = {
        "com.lysztech.mybatis.page.PageResult",
        "com.lysztech.core.web.domain.R",
        "com.lysztech.log.annotation.AuditLog",
        "jakarta.validation.Valid",
        f"{config.base_package}.{config.dto_package}.{table.class_name}CreateDTO",
        f"{config.base_package}.{config.dto_package}.{table.class_name}PageQueryDTO",
        f"{config.base_package}.{config.dto_package}.{table.class_name}UpdateDTO",
        f"{config.base_package}.{config.service_package}.{table.class_name}Service",
        f"{config.base_package}.{config.vo_package}.{table.class_name}VO",
        "lombok.RequiredArgsConstructor",
        "org.springframework.web.bind.annotation.GetMapping",
        "org.springframework.web.bind.annotation.PostMapping",
        "org.springframework.web.bind.annotation.RequestBody",
        "org.springframework.web.bind.annotation.RequestMapping",
        "org.springframework.web.bind.annotation.RequestParam",
        "org.springframework.web.bind.annotation.RestController",
    }
    return "\n".join(
        [
            f"package {config.base_package}.{config.controller_package};",
            "",
            render_imports(imports),
            "",
            f"/** {comment} */",
            "@RestController",
            "@RequiredArgsConstructor",
            f'@RequestMapping("{request_path}")',
            f"public class {table.class_name}Controller {{",
            "",
            f"    private final {table.class_name}Service {table.entity_var_name}Service;",
            "",
            "    /**",
            f"     * {comment}分页查询",
            "     *",
            "     * @param queryDto 分页查询参数",
            "     * @return 分页结果",
            "     */",
            '    @PostMapping("/page")',
            f'    @AuditLog(operation = "{comment}分页查询")',
            f"    public R<PageResult<{table.class_name}VO>> page(@RequestBody(required = false) {table.class_name}PageQueryDTO queryDto) {{",
            f"        return R.ok({table.entity_var_name}Service.page(queryDto));",
            "    }",
            "",
            "    /**",
            f"     * {comment}详情",
            "     *",
            f"     * @param {primary_key_field_name} 主键ID",
            "     * @return 详情",
            "     */",
            '    @GetMapping("/detail")',
            f'    @AuditLog(operation = "{comment}详情")',
            f"    public R<{table.class_name}VO> detail(@RequestParam {primary_key_type} {primary_key_field_name}) {{",
            f"        return R.ok({table.entity_var_name}Service.detail({primary_key_field_name}));",
            "    }",
            "",
            "    /**",
            f"     * {comment}新增",
            "     *",
            "     * @param createDto 新增参数",
            "     * @return 是否成功",
            "     */",
            '    @PostMapping("/create")',
            f'    @AuditLog(operation = "{comment}新增")',
            f"    public R<Boolean> create(@Valid @RequestBody {table.class_name}CreateDTO createDto) {{",
            f"        return R.ok({table.entity_var_name}Service.create(createDto));",
            "    }",
            "",
            "    /**",
            f"     * {comment}修改",
            "     *",
            "     * @param updateDto 修改参数",
            "     * @return 是否成功",
            "     */",
            '    @PostMapping("/update")',
            f'    @AuditLog(operation = "{comment}修改")',
            f"    public R<Boolean> update(@Valid @RequestBody {table.class_name}UpdateDTO updateDto) {{",
            f"        return R.ok({table.entity_var_name}Service.update(updateDto));",
            "    }",
            "",
            "    /**",
            f"     * {comment}删除",
            "     *",
            f"     * @param {primary_key_field_name} 主键ID",
            "     * @return 是否成功",
            "     */",
            '    @PostMapping("/delete")',
            f'    @AuditLog(operation = "{comment}删除")',
            f"    public R<Boolean> delete(@RequestParam {primary_key_type} {primary_key_field_name}) {{",
            f"        return R.ok({table.entity_var_name}Service.delete({primary_key_field_name}));",
            "    }",
            "}",
        ]
    )
