SQL_TYPE_TO_JAVA = {
    "bigint": "Long",
    "binary": "byte[]",
    "bit": "Boolean",
    "blob": "byte[]",
    "bool": "Boolean",
    "boolean": "Boolean",
    "char": "String",
    "date": "LocalDate",
    "datetime": "LocalDateTime",
    "decimal": "BigDecimal",
    "double": "Double",
    "float": "Float",
    "int": "Integer",
    "integer": "Integer",
    "json": "String",
    "longtext": "String",
    "mediumint": "Integer",
    "mediumtext": "String",
    "numeric": "BigDecimal",
    "smallint": "Integer",
    "text": "String",
    "time": "LocalTime",
    "timestamp": "LocalDateTime",
    "tinyint": "Integer",
    "varchar": "String",
}

SQL_TYPE_TO_MYSQL = {
    "bigint": "BIGINT",
    "binary": "BINARY",
    "bit": "BIT",
    "blob": "BLOB",
    "bool": "TINYINT",
    "boolean": "TINYINT",
    "char": "CHAR",
    "date": "DATE",
    "datetime": "DATETIME",
    "decimal": "DECIMAL",
    "double": "DOUBLE",
    "float": "FLOAT",
    "int": "INT",
    "integer": "INT",
    "json": "JSON",
    "longtext": "LONGTEXT",
    "mediumint": "MEDIUMINT",
    "mediumtext": "MEDIUMTEXT",
    "numeric": "DECIMAL",
    "smallint": "SMALLINT",
    "text": "TEXT",
    "time": "TIME",
    "timestamp": "TIMESTAMP",
    "tinyint": "TINYINT",
    "varchar": "VARCHAR",
}

JAVA_TYPE_IMPORTS = {
    "BigDecimal": "java.math.BigDecimal",
    "LocalDate": "java.time.LocalDate",
    "LocalDateTime": "java.time.LocalDateTime",
    "LocalTime": "java.time.LocalTime",
}

DEFAULT_BASE_ENTITY_FIELDS = {
    "id": ("Long", "主键ID"),
    "remark": ("String", "备注"),
    "create_by": ("Long", "创建人ID"),
    "create_time": ("LocalDateTime", "创建时间"),
    "create_user_id": ("String", "创建人ID"),
    "update_by": ("Long", "更新人ID"),
    "update_time": ("LocalDateTime", "更新时间"),
    "update_user_id": ("String", "更新人ID"),
    "delete_by": ("Long", "删除人ID"),
    "delete_time": ("LocalDateTime", "删除时间"),
}

PACKAGE_KEYS = (
    "base_package",
    "package_name",
    "project_package",
    "package_path",
)

KNOWN_PACKAGE_SUFFIXES = (
    ".service.impl",
    ".common.entity",
    ".controller",
    ".service",
    ".mapper",
    ".entity",
    ".dto",
    ".vo",
)
